/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delfinen.presentation;

import delfinen.logic.ControllerTrainer;
import delfinen.logic.Disciplin;
import delfinen.logic.Team;
import delfinen.logic.TrainingResult;
import java.util.ArrayList;

public class GUITop5 extends javax.swing.JFrame
{

    private ControllerTrainer c;
    private final Team team;

    public GUITop5(Team team)
    {
        initComponents();

        this.team = team;

        c = new ControllerTrainer();

        tcrawl.getTableHeader()
                .getColumnModel().getColumn(0).setHeaderValue("Swimmer");
        tcrawl.getTableHeader()
                .getColumnModel().getColumn(1).setHeaderValue("Date");
        tcrawl.getTableHeader()
                .getColumnModel().getColumn(2).setHeaderValue("Time");

        ArrayList<TrainingResult> crawl = c.top5(team, Disciplin.CRAWL);

        for (int i = 0;
                i < crawl.size();
                i++)
        {
            tcrawl.getModel().setValueAt(crawl.get(i).getMember().getName(), i, 0);
            tcrawl.getModel().setValueAt(crawl.get(i).getDate(), i, 1);
            tcrawl.getModel().setValueAt(crawl.get(i).getTime(), i, 2);
        }

        tbutterfly.getTableHeader()
                .getColumnModel().getColumn(0).setHeaderValue("Swimmer");
        tbutterfly.getTableHeader()
                .getColumnModel().getColumn(1).setHeaderValue("Date");
        tbutterfly.getTableHeader()
                .getColumnModel().getColumn(2).setHeaderValue("Time");

        ArrayList<TrainingResult> butterfly = c.top5(team, Disciplin.BUTTERFLY);

        for (int i = 0;
                i < butterfly.size();
                i++)
        {
            tbutterfly.getModel().setValueAt(butterfly.get(i).getMember().getName(), i, 0);
            tbutterfly.getModel().setValueAt(butterfly.get(i).getDate(), i, 1);
            tbutterfly.getModel().setValueAt(butterfly.get(i).getTime(), i, 2);
        }

        tbreaststroke.getTableHeader()
                .getColumnModel().getColumn(0).setHeaderValue("Swimmer");
        tbreaststroke.getTableHeader()
                .getColumnModel().getColumn(1).setHeaderValue("Date");
        tbreaststroke.getTableHeader()
                .getColumnModel().getColumn(2).setHeaderValue("Time");

        ArrayList<TrainingResult> breaststroke = c.top5(team, Disciplin.BREASTSTROKE);

        for (int i = 0;
                i < breaststroke.size();
                i++)
        {
            tbreaststroke.getModel().setValueAt(breaststroke.get(i).getMember().getName(), i, 0);
            tbreaststroke.getModel().setValueAt(breaststroke.get(i).getDate(), i, 1);
            tbreaststroke.getModel().setValueAt(breaststroke.get(i).getTime(), i, 2);
        }

        tbackcrawl.getTableHeader()
                .getColumnModel().getColumn(0).setHeaderValue("Swimmer");
        tbackcrawl.getTableHeader()
                .getColumnModel().getColumn(1).setHeaderValue("Date");
        tbackcrawl.getTableHeader()
                .getColumnModel().getColumn(2).setHeaderValue("Time");

        ArrayList<TrainingResult> backcrawl = c.top5(team, Disciplin.BACKCRAWL);

        for (int i = 0;
                i < backcrawl.size();
                i++)
        {
            tbackcrawl.getModel().setValueAt(backcrawl.get(i).getMember().getName(), i, 0);
            tbackcrawl.getModel().setValueAt(backcrawl.get(i).getDate(), i, 1);
            tbackcrawl.getModel().setValueAt(backcrawl.get(i).getTime(), i, 2);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tcrawl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbreaststroke = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbackcrawl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        goback = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbutterfly = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tcrawl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tcrawl);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Top 5");

        tbreaststroke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane3.setViewportView(tbreaststroke);

        tbackcrawl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane4.setViewportView(tbackcrawl);

        jLabel2.setText("Butterfly");

        jLabel3.setText("Crawl");

        jLabel4.setText("Backcrawl");

        jLabel5.setText("Breaststroke");

        goback.setText("Go back");
        goback.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                gobackActionPerformed(evt);
            }
        });

        tbutterfly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane5.setViewportView(tbutterfly);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)
                        .addGap(349, 349, 349)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel4)
                        .addGap(324, 324, 324)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goback)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 58, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(goback)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_gobackActionPerformed
    {//GEN-HEADEREND:event_gobackActionPerformed
        this.setVisible(false);
        new GUITrainerMenu().setVisible(true);
    }//GEN-LAST:event_gobackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUITop5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUITop5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUITop5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUITop5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbackcrawl;
    private javax.swing.JTable tbreaststroke;
    private javax.swing.JTable tbutterfly;
    private javax.swing.JTable tcrawl;
    // End of variables declaration//GEN-END:variables
}
